In [1]:
import numpy as np
mylist = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mylist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
np.random.rand(10)

array([0.59514472, 0.01677576, 0.67026625, 0.51654975, 0.30099226,
       0.70953829, 0.11911285, 0.76207301, 0.29738382, 0.58439554])

In [3]:
np.random.rand(4,4)

array([[0.13111217, 0.33523904, 0.76119502, 0.52522641],
       [0.76068414, 0.42411842, 0.77791535, 0.37028673],
       [0.05970044, 0.1620299 , 0.45618163, 0.61391461],
       [0.39377252, 0.95418017, 0.10637649, 0.82247754]])

In [4]:
np.random.rand(4)

array([0.01349731, 0.88894379, 0.41346907, 0.7720397 ])

In [5]:
np.random.randint(0,10,1)

array([5])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ec = [1200,3400,2900,1800,2500]
energy_consumption = np.array(ec)
print("Energy Consumption (in MWH) for Diffrent renewable Sources ")
print(energy_consumption)

Energy Consumption (in MWH) for Diffrent renewable Sources 
[1200 3400 2900 1800 2500]


**numpy**

In [12]:
type(ec)

list

In [13]:
type(energy_consumption)

numpy.ndarray

In [15]:
A= np.ones(4)
A2 = np.ones((2,2))
print(A)
print("\n ",A2)

[1. 1. 1. 1.]

  [[1. 1.]
 [1. 1.]]


In [16]:
M = np.zeros(4)
print(M)

[0. 0. 0. 0.]


In [19]:
M = np.identity(4)
print(M)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
total_consumption = np.sum(energy_consumption)
print(f"total Energy Consumption: {total_consumption}mwh")

11800
total Energy Consumption: 11800mwh


In [23]:
total_consumption = np.mean(energy_consumption)#mean
print(f"total Energy Consumption: {total_consumption:.2f}mwh")

total Energy Consumption: 2360.00mwh


In [26]:
total_consumption = np.std(energy_consumption)
print(f"total Energy Consumption: {total_consumption:.2f}mwh")

total Energy Consumption: 781.28mwh


In [27]:
energy_consumption2 = np.array([1200,3400,2900,1800,2500,1800])
reshaped_array = energy_consumption2.reshape((3,2))
print("reshaped Energy Computation Array (3*2)")
print(reshaped_array)

reshaped Energy Computation Array (3*2)
[[1200 3400]
 [2900 1800]
 [2500 1800]]


In [28]:
reshaped_array.flatten()
resize_array=np.resize(reshaped_array,(3,3))
resize_array

array([[1200, 3400, 2900],
       [1800, 2500, 1800],
       [1200, 3400, 2900]])

In [29]:
resize_array = np.resize(reshaped_array,(3,3))
resize_array

array([[1200, 3400, 2900],
       [1800, 2500, 1800],
       [1200, 3400, 2900]])